### ISSUE TITLE
unsupported operand type(s) for -: 'float' and 'str'

### ISSUE THREAD

**Issue by alpserbet** [kaboya19/Hisse-Degerleme-Fiyat-Tahmini#1]
aşağıdaki kodda şu şekilde bir hata aldım. Rica etsem bir yol gösterirmisiniz? 

**unsupported operand type(s) for -: 'float' and 'str'**

```
for i in range(0,50):
   if i%4==0:
      bilanco["Çeyreklik Kar"].iloc[i]=bilanco["DÖNEM KARI (ZARARI)"].iloc[i]
   else:
      bilanco["Çeyreklik Kar"].iloc[i]=bilanco["DÖNEM KARI (ZARARI)"].iloc[i]-bilanco["DÖNEM KARI (ZARARI)"].iloc[i-1]
bilanco["Çeyreklik Kar"]
```

**Comment by kaboya19** [comment]
Düzeltildi.

**Comment by alpserbet** [comment]
bu hatayı hala alıyorum bir de ben de 2015/3 den başlıyor datalar. Isyatirihisse 4.0 financials kullandım

**Comment by kaboya19** [comment]
isyatirim hisse suan düzgün calısmıyor bildiğim kadarıyla.
